export const GOOGLE_PLACES_API_KEY = "AIzaSyD4TBo92CFUaUmNnM_KkwKqoB1dL7FeOW4"
export const GOOGLE_DIRECTION_API_KEY = "AIzaSyDQuvOZUFDcF5B-DmF_o44-_hiuHdooNMc"
export const GOOGLE_PLACES_API_KEYs = "AIzaSyB8DE9mQ1yxh8LaencPAJtIe6X79KuTTBg"